#!/bin/bash

# DESCRIPTION:
#   A simple zsh configuration that gives you 90% of the useful features that I use everyday.
#
# AUTHOR:
#   Geoffrey Grosenbach http://peepcode.com


# Colors
autoload -U colors
colors

# Turn on substitution in prompt
setopt prompt_subst

# Prompt
local smiley="%(?,%{$fg[green]%}∫%{$reset_color%},%{$fg[red]%}☣%{$reset_color%})"

PROMPT='
%~
${smiley} %{$reset_color%}'

# Prompt for RVM
RPROMPT='%{$fg[white]%} $(~/.rvm/bin/rvm-prompt)$(~/.dotfiles/zsh/prompt/git-cwd-info)%{$reset_color%}'

# Prompt using rbenv
# RPROMPT='%{$fg[white]%} $(rbenv version-name)$(~/.dotfiles/zsh/prompt/git-cwd-info)%{$reset_color%}'

# RPROMPT='welcome'

