#!/bin/bash

# DESCRIPTION:
#   A simple zsh configuration that gives you 90% of the useful features that I use everyday.
#
# AUTHOR:
#   Geoffrey Grosenbach http://peepcode.com


# Colors
autoload -U colors
colors
setopt prompt_subst

# Prompt
local smiley="%(?,%{$fg[green]%}∫%{$reset_color%},%{$fg[red]%}☣%{$reset_color%})"

PROMPT='
%~
${smiley} %{$reset_color%}'

# Prompt for RVM
RPROMPT='%{$fg[white]%} $(~/.rvm/bin/rvm-prompt)$(~/dotfiles/zsh/prompt/git-cwd-info)%{$reset_color%}'

# Prompt using rbenv
# RPROMPT='%{$fg[white]%} $(rbenv version-name)$(~/dotfiles/zsh/prompt/git-cwd-info)%{$reset_color%}'

# RPROMPT='welcome'


# Show completion on first TAB
setopt menucomplete

# Load completions for Ruby, Git, etc.
autoload compinit
compinit
